import { Todo } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { MouseEvent, useState } from "react";
import { trpc } from "../utils/trpc";

type TodoCardProps = {
  todo: Todo;
  handleToggle: Function;
  handleDelete: Function;
};

// const TodoArray: Array<Todo> = [
//   { description: "Do chores", isComplete: false },
//   { description: "Eat shit", isComplete: false },
//   { description: "Watch TV", isComplete: false },
//   { description: "Drink METH", isComplete: false },
//   { description: "Destroy cars", isComplete: false },
//   { description: "Have Fun", isComplete: false },
//   { description: "Fail", isComplete: false },
// ];

const Home: NextPage = () => {
  // const TodoArray =  ?? [];
  // console.log(TodoArray);

  const utils = trpc.useContext();
  const todosQuery = trpc.useQuery(["todo.getAll"]);
  const setIsComplete = trpc.useMutation("todo.setIsComplete", {
    async onSuccess() {
      await utils.invalidateQueries(["todo.getAll"]);
    },
  });
  const deleteTodoQuery = trpc.useMutation("todo.delete", {
    async onSuccess() {
      await utils.invalidateQueries(["todo.getAll"]);
    },
  });

  // console.log("todos data is", todosQuery.data);
  // const [todos, setTodos] = useState(todosData ? [...todosData] : []);

  const toggleTodo = (atIndex: number, newValue: boolean) => {
    setIsComplete.mutate({
      id: atIndex,
      isComplete: newValue,
    });
    console.log("toggled todo");
  };

  const deleteTodo = (atIndex: number) => {
    deleteTodoQuery.mutate({ id: atIndex });
    console.log("deleted todo");
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex select-none flex-col gap-2 items-center justify-center min-h-screen p-4">
        {todosQuery.data ? (
          todosQuery.data.map((todoItem) => {
            return (
              // <div onClick={() => toggleTodo(index)}>
              <TodoCard
                todo={todoItem}
                key={todoItem.id}
                handleToggle={() => {
                  toggleTodo(todoItem.id, !todoItem.isComplete);
                }}
                handleDelete={() => {
                  deleteTodo(todoItem.id);
                }}
              />
              // </div>
            );
          })
        ) : (
          <></>
        )}
      </main>
    </>
  );
};

const TodoCard = ({ todo, handleToggle, handleDelete }: TodoCardProps) => {
  //, handleClick
  return (
    <section
      className="flex flex-row justify-between items-center w-96 p-6 duration-500 border-2 border-gray-500 relative rounded shadow-xl motion-safe:hover:scale-105"
      onClick={() => handleToggle()}
    >
      <p
        className="w-4 h-4 bg-red-600 text-white z-0 flex items-center justify-center rounded -m-1.5 absolute top-0 right-0 motion-safe:hover:scale-[2]"
        onClick={(e) => {
          handleDelete();
          e.stopPropagation();
        }}
      >
        X
      </p>
      <h2 className="text-lg text-gray-700">{todo.description}</h2>
      <p className="text-sm text-gray-600">
        is complete: {todo.isComplete ? "true" : "false"}
      </p>
    </section>
  );
};

export default Home;
